apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: sse-adapter-base

resources:
  - deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: distributed-sse
  app.kubernetes.io/managed-by: kustomize
