apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: llm-base

resources:
  - deployment.yaml
  - redis.yaml

commonLabels:
  app.kubernetes.io/part-of: distributed-sse
  app.kubernetes.io/managed-by: kustomize
